include:
  - template: Code-Quality.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - local: .gitlab-ci/_prereqs.yml
  - local: .gitlab-ci/build.yml
  - local: .gitlab-ci/test-matrix.yml

code_quality:
  services:
    - name: docker:stable-dind
      command: [--storage-driver, aufs]


stages:
  - build
  - test
  - release

release:
  stage: release
  needs:
    - job: build
      artifacts: true
  only:
    - tags
  script:
    - ''