
.php70-linux:
  image: php:7.0
  tags:
    - linux
    - php
.php71-linux:
  image: php:7.1
  tags:
    - linux
    - php
.php72-linux:
  image: php:7.2
  tags:
    - linux
    - php
.php73-linux:
  image: php:7.3
  tags:
    - linux
    - php
.php74-linux:
  image: php:7.4
  tags:
    - linux
    - php
.php80-linux:
  image: php:8.0
  tags:
    - linux
    - php
