.base:
  before_script:
  - |
    echo "Install base packages"
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential \
      libssl-dev \
      gnupg \
      libfreetype6-dev \
      libicu-dev \
      libjpeg62-turbo-dev \
      libmcrypt-dev \
      libonig-dev \
      libxml2-dev \
      vim \
      wget \
      unzip \
      git \
      subversion \
      default-mysql-client

    echo "Install composer"
    curl -sS -L https://getcomposer.org/installer | php
    mv composer.phar /usr/local/bin/composer

    echo "Install PHP extensions"
    docker-php-ext-install -j$(nproc) iconv intl xml soap opcache pdo pdo_mysql mysqli mbstring gd
  - |
    echo "Install NVM"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
    if [ -s "$HOME/.nvm/nvm.sh" ]; then \. "$HOME/.nvm/nvm.sh"; fi
    echo "Install node"
    nvm install '14.15.1'
    nvm use '14.15.1'
  - |
    composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress
    mkdir -p tools
    ln -sf $HOME/.composer/vendor/bin/phpunit tools/phpunit
    git clone -b master --depth 1 https://github.com/WordPress/WordPress-Coding-Standards.git /tmp/sniffs
    ./tools/phpcs --config-set installed_paths /tmp/sniffs
  - |
    composer global require phpunit/phpunit:^6 --prefer-dist --no-interaction --no-progress
    mkdir -p tools
    ln -sf $HOME/.composer/vendor/bin/phpunit tools/phpunit
